language: rust
rust: stable
cache: cargo

install:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo clippy --release
  - cargo fmt -- --check
  - cargo build --release
  - cargo test --release
