[package]
name = "aprt"
version = "0.1.0"
authors = ["cezarmathe <me@cezarmathe.com>"]
edition = "2018"

[lib]
name = "aprt"
path = "src/lib.rs"

[[bin]]
name = "aprt"
path = "src/main.rs"

[dependencies]
